export const actionConstants = {
  TODO_TEXT_REQUEST: 'TODO_TEXT_REQUEST',
  TODO_TEXT_SUCCESS: 'TODO_TEXT_SUCCESS',
  TODO_TODO_REQUEST: 'TODO_TODO_REQUEST',
  TODO_TODO_SUCCESS: 'TODO_TODO_SUCCESS',
  TODO_TODO_FAILURE: 'TODO_TODO_FAILURE',
  TODO_ALTER_STATE_REQUEST: 'TODO_ALTER_STATE_REQUEST',
  TODO_ALTER_STATE_SUCCESS: 'TODO_ALTER_STATE_SUCCESS',
  TODO_DELETE_REQUEST: 'TODO_DELETE_REQUEST',
  TODO_DELETE_SUCCESS: 'TODO_DELETE_SUCCESS',
  TOP_MENU_VALUE_REQUEST: 'TOP_MENU_VALUE_REQUEST',
  TOP_MENU_VALUE_SUCCESS: 'TOP_MENU_VALUE_SUCCESS',
};
