export const actionConstants = {
  TODO_TEXT_REQUEST: 'TODO_TEXT_REQUEST',
  TODO_TEXT_SUCCESS: 'TODO_TEXT_SUCCESS',
  TODO_TODO_REQUEST: 'TODO_TODO_REQUEST',
  TODO_TODO_SUCCESS: 'TODO_TODO_SUCCESS',
  TODO_TODO_FAILURE: 'TODO_TODO_FAILURE',
};
