export const actionConstants = {
  WALKING_FIGURE_GET_IMG0: 'WALKING_FIGURE_GET_IMG0',
  WALKING_FIGURE_GET_IMG1: 'WALKING_FIGURE_GET_IMG1',
  WALKING_FIGURE_GET_IMG2: 'WALKING_FIGURE_GET_IMG2',
  WALKING_FIGURE_GET_IMG3: 'WALKING_FIGURE_GET_IMG3',
  WALKING_FIGURE_SET_IMG0: 'WALKING_FIGURE_SET_IMG0',
  WALKING_FIGURE_SET_IMG1: 'WALKING_FIGURE_SET_IMG1',
  WALKING_FIGURE_SET_IMG2: 'WALKING_FIGURE_SET_IMG2',
  WALKING_FIGURE_SET_IMG3: 'WALKING_FIGURE_SET_IMG3',
};
